name: Terraform Deployment Pipeline
on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_REGION: eu-west-2
    steps:
      #Fetch code from the repository onot runner
      - name: Checkout code 
        uses: actions/checkout@v4

      #Setup version of terraform to use in the pipeline
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
      
      #Connect to remote backend to store terraform state file
      - name: Terraform Init
        run: terraform init

      #Terraform Plan to check for any changes in the infrastructure
      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: deploy-to-production
    needs: terraform-plan #prevent apply until plan is successful
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve